modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Initially/issues"
license="MIT"

[[mods]]
modId="initially"
version="${file.jarVersion}"
displayName="Initially"
displayURL="https://www.curseforge.com/minecraft/mc-mods/initially"
authors="Mrbysco, ShyNieke"
description='''
Initializes your inventory with items specified in the config.
'''
[[dependencies.initially]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"