modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/Initially/issues"
license="MIT"

[[mods]]
modId="initially"
version="${file.jarVersion}"
displayName="Initially"
displayURL="https://www.curseforge.com/minecraft/mc-mods/initially"
authors="Mrbysco, ShyNieke"
description='''
Initializes your inventory with items specified in the config.
'''
[[dependencies.initially]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.initially]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"